### ISSUE TITLE
Implement Set Points (water,cooling, heating), as well as all the values from Heating Curve

### ISSUE THREAD

**Issue by flautze** [pattisonmichael/waterkotte-integration#34]
As mentioned on Home Assist forum,
I really would appreciate the following values in the integration (from my perspective importance is following the order in which I listed below)
- set points for heating, cooling, water
- heating adjustment (where you can adjust the setpoint in steps of 0,5*C from -2 to +2
- All values from the heating curve (Tnorm Aussen, Heizgrenze, T Heizgrenze, T Norm)
- Heating curve adjustment if PV is active.
- 
thanks for your work and best regards,
Felix

**Comment by pattisonmichael** [comment]
I'm going to release a new version soon.
Could you please specify the Tags of the values you want (if you know them).
I might also need some volunteers to collect the data via the web app for me.

**Comment by flautze** [comment]
Hello, what type of tag do you need?
I could find out the tags in openHAB integration, maybe also I have a Modbus manual somewhere specifying the value, modbus adress, Typ and description. It is in German however.

for example Heatibg curve values are
nviHeizkreisNorm
nviNormAussen
nviTHeozgrenze
nviTHeizgrenzeSoll

Temperature_water_set   Would be setpoint for water (water temp +/- adjustments)

adapt_heating.  Would be the setpoint where you can add - between -2 and +2 in steps of 0,5.

tempchange_heating_pv
tempchange_cooling_pv
tenpchange_pool_pv
  Would be adjustments to temperature if Pv is active.

hysteresis_heating would be the hysteresis value (changeable)

but I don’t know if these are the tags you are talking about.

if you tell me how I can help you with data via web app let me know. I would be wiling to.

**Comment by flautze** [comment]
Ok. I think I found it
adapt heating = I263 can have values between 0 and 8
0 corresponds to -2.0 degree, 4 = no adjustment and 8 = +2.0 degree.

i will look for the others.

**Comment by pattisonmichael** [comment]
I added those already earlier :)
But yes that's what I'm looking for.
Give 0.0.11 a try and see if it works for you.

**Comment by flautze** [comment]
I will. Also added the setpoints for cooling/water.
Let you know later.

**Comment by flautze** [comment]
Water setpoint works
Temperature heating adapt works
Temperature cooling set works
Temperature pool set points have different structure. I think all the setpoints but the adapt should have the same layout as the pool, where you can see the value.

![image](https://user-images.githubusercontent.com/6823055/219417369-898fd903-b120-4c43-aabd-9f01d217193a.jpg)

the norm and limit don’t seem to work.

![image](https://user-images.githubusercontent.com/6823055/219417884-8fd8bc6d-534b-4503-80f8-0ce5489e459a.jpg)


Found something on openHAB binding

hysteresis = A61

norm outside = A91
Heating norm = A92

heating Limit = A93
Heating limit set = A94

**Comment by flautze** [comment]
Also note,
there is always 2setpoints:
Water Setpoint 1 = Setpoint - minus adjusments (for example if you have offset during hours).
Water Setpoint 2 = actually what you set as water temperature
here you find the info, where I look up the registers:
https://github.com/openhab/openhab1-addons/commit/86011afd2ef44fd76644c95b85e5285ad9d78df8
 // German: Sollwert Warmwassertemperatur === 10 ° for me since I have an offset.
    TYPE_TEMPERATURE_WATER_SET {               
        {
            command = "temperature_water_set";
            itemClass = NumberItem.class;
            tagName = "A37";
        }
    },
    // German: Sollwertvorgabe Warmwassertemperatur   = 43,5 for me since I have an offset.
    TYPE_TEMPERATURE_WATER_SET2 {
        {
            command = "temperature_water_set2";
            itemClass = NumberItem.class;
            tagName = "A38";
        }
    },

**Comment by pattisonmichael** [comment]
I think this has all been added now. Could you check?
