### ISSUE TITLE
Is development support wanted?!

### ISSUE THREAD

**Issue by marq24** [pattisonmichael/waterkotte-integration#36]
@pattisonmichael - as you might have noticed I have forked your repo and started to work on (some) of the additional TAGs that would be required to implement heating curve adjustments and few other things)... Before I would make a PR I would like to get in contact with you in order to hear from you, if you are in general interested to get some support in developing the waterkotte-integration?

I have to admit, that I am a totally ruby newbee - also i just started with Home Assistent two weeks ago - so my current code might look extremely ugly to you. I just started with the fork in order to adjust your current implementation to my personal requirements [e.g. fetching max of 75 tags (instead of 10)]. I have no intention to do any kind of advertisement in the home assistant community (it's for my personal usage only) - so if you would appreciate support in the development (which implies to deal with a second option) - it would be cool if you would get in contact with me e.g. by email: marquardt24 [] gmail (we can communicate in German).

kind regards
Matthias

**Comment by pattisonmichael** [comment]
A bit late, but I'm always happy to get help. I'm just not looking at GitHub much and work on my local Gitea :)
Best is to use the HA Forum to get in touch and collaborate.
[Forum](https://community.home-assistant.io/t/waterkotte-heatpump-integration/522503)
